import type { Metadata } from 'next';
import { sons } from '~/app/_styles/fonts';
import '~/app/_styles/globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${sons.variable}`}>
			<body>{children}</body>
		</html>
	);
}
